title: Pattern Library
description: A collection of patterns to help you build up a style guide for your site

baseurl: /
url:     /styleguide

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:
  - _config.yaml
  - example.info
  - Gemfile
  - Gemfile.lock
  - README.md
keep_files:  ['.git']
timezone:    Europe/London
markdown:    kramdown
permalink:   pretty
highlighter: pygments

collections:
  - patterns

sass:
  sass_dir: ./style/_sass
